import { normalizeName } from './normalize-name';

export interface IconItem {
  name: string;
  icon: string;              // filename stem for /icons/{icon}.webp
  iconUrl?: string;          // full URL (custom icons); takes precedence when present
  category: string;
  aliases?: string[];
}

export const ICON_ITEMS: IconItem[] = [
  // 蔬菜
  { name: '娃娃菜', icon: 'baby-cabbage', category: '蔬菜' },
  { name: '西红柿', icon: 'tomato', category: '蔬菜', aliases: ['番茄'] },
  { name: '洋葱', icon: 'onion', category: '蔬菜' },
  { name: '大蒜', icon: 'garlic', category: '蔬菜' },
  { name: '生姜', icon: 'ginger', category: '蔬菜' },
  { name: '韭菜', icon: 'chives', category: '蔬菜' },
  { name: '小葱', icon: 'scallion', category: '蔬菜', aliases: ['香葱'] },
  { name: '白萝卜', icon: 'daikon', category: '蔬菜' },
  // 肉类
  { name: '五花肉', icon: 'pork-belly', category: '肉蛋' },
  { name: '猪排骨', icon: 'pork-ribs', category: '肉蛋', aliases: ['排骨'] },
  { name: '牛肋条', icon: 'beef-short-rib-strips', category: '肉蛋' },
  { name: '牛仔骨', icon: 'beef-short-ribs', category: '肉蛋' },
  { name: '整鸡', icon: 'whole-chicken', category: '肉蛋' },
  // 蛋奶
  { name: '鸡蛋', icon: 'eggs', category: '肉蛋' },
  { name: '牛奶', icon: 'milk', category: '乳制品' },
  // 主食
  { name: '大米', icon: 'rice', category: '主食', aliases: ['米'] },
  { name: '速冻饺子', icon: 'frozen-dumplings', category: '主食', aliases: ['饺子'] },
  // 调料
  { name: '食用油', icon: 'cooking-oil', category: '调料' },
  { name: '盐', icon: 'salt', category: '调料' },
  { name: '桂皮', icon: 'cinnamon-bark', category: '调料' },
  { name: '八角', icon: 'star-anise', category: '调料' },
  { name: '香叶', icon: 'bay-leaves', category: '调料' },
  { name: '花椒', icon: 'sichuan-pepper', category: '调料' },
  // 日用
  { name: '纸巾', icon: 'tissue-box', category: '日用', aliases: ['抽纸'] },
  { name: '卫生纸', icon: 'toilet-paper', category: '日用', aliases: ['卷纸'] },
  { name: '厨房纸巾', icon: 'kitchen-towel', category: '日用' },
  { name: '垃圾袋', icon: 'trash-bags', category: '日用' },
  { name: '保鲜膜', icon: 'cling-wrap', category: '日用' },
  { name: '洗手液', icon: 'hand-soap', category: '日用' },
  { name: '沐浴露', icon: 'body-wash', category: '日用' },
  { name: '洗发水', icon: 'shampoo', category: '日用' },
  { name: '护发素', icon: 'conditioner', category: '日用' },
  { name: '牙膏', icon: 'toothpaste', category: '日用' },
  { name: '牙刷', icon: 'toothbrush', category: '日用' },
  // 烘焙
  { name: '低筋面粉', icon: 'cake-flour', category: '烘焙' },
  { name: '高筋面粉', icon: 'bread-flour', category: '烘焙' },
  { name: '炼乳', icon: 'condensed-milk', category: '烘焙' },
  // 饮料
  { name: '矿泉水', icon: 'water', category: '饮料' },
  // 水果
  { name: '苹果', icon: 'apple', category: '水果' },
  { name: '香蕉', icon: 'banana', category: '水果' },
  { name: '橙子', icon: 'orange', category: '水果' },
  { name: '葡萄', icon: 'grapes', category: '水果' },
  { name: '草莓', icon: 'strawberry', category: '水果' },
  { name: '西瓜', icon: 'watermelon', category: '水果' },
  { name: '梨', icon: 'pear', category: '水果' },
  { name: '柠檬', icon: 'lemon', category: '水果' },
  { name: '牛油果', icon: 'avocado', category: '水果' },
  { name: '蓝莓', icon: 'blueberry', category: '水果' },
  { name: '虾', icon: 'shrimp', category: '海鲜' },
  { name: '鱼', icon: 'fish', category: '海鲜' },
  { name: '三文鱼', icon: 'salmon', category: '海鲜' },
  { name: '蛤蜊', icon: 'clams', category: '海鲜' },
  { name: '螃蟹', icon: 'crab', category: '海鲜' },
  { name: '土豆', icon: 'potato', category: '蔬菜' },
  { name: '青椒', icon: 'green-pepper', category: '蔬菜' },
  { name: '黄瓜', icon: 'cucumber', category: '蔬菜' },
  { name: '菠菜', icon: 'spinach', category: '蔬菜' },
  { name: '胡萝卜', icon: 'carrot', category: '蔬菜' },
  { name: '玉米', icon: 'corn', category: '蔬菜' },
  { name: '蘑菇', icon: 'mushroom', category: '蔬菜' },
  { name: '西兰花', icon: 'broccoli', category: '蔬菜' },
  { name: '芹菜', icon: 'celery', category: '蔬菜' },
  { name: '生菜', icon: 'lettuce', category: '蔬菜' },
  { name: '豆腐', icon: 'tofu', category: '豆制品' },
  { name: '面条', icon: 'noodles', category: '主食' },
  { name: '面包', icon: 'bread', category: '主食' },
  { name: '意面', icon: 'pasta', category: '主食' },
  { name: '酸奶', icon: 'yogurt', category: '乳制品' },
  { name: '奶酪', icon: 'cheese', category: '乳制品' },
  { name: '可乐', icon: 'cola', category: '饮料' },
  { name: '冰红茶', icon: 'iced-tea', category: '饮料' },
  { name: '桃汁', icon: 'peach-juice', category: '饮料' },
  { name: '豆浆', icon: 'soy-milk', category: '饮料' },
  { name: '咖喱块', icon: 'curry-block', category: '调料' },
  { name: '生抽', icon: 'light-soy-sauce', category: '调料' },
  { name: '老抽', icon: 'dark-soy-sauce', category: '调料' },
  { name: '料酒', icon: 'cooking-wine', category: '调料' },
  { name: '糖', icon: 'sugar', category: '调料' },
  { name: '蚝油', icon: 'oyster-sauce', category: '调料' },
  { name: '豆瓣酱', icon: 'doubanjiang', category: '调料' },
  { name: '番茄酱', icon: 'ketchup', category: '调料' },
  { name: '洗衣球', icon: 'laundry-pods', category: '日用' },
  { name: '洗洁精', icon: 'dish-soap', category: '日用' },
  { name: '小苏打', icon: 'baking-soda', category: '烘焙' },
  { name: '五香粉', icon: 'five-spice', category: '调料' },
  { name: '芦笋', icon: 'asparagus', category: '蔬菜' },
  { name: '豆芽', icon: 'bean-sprouts', category: '蔬菜' },
  { name: '彩椒', icon: 'bell-pepper', category: '蔬菜' },
  { name: '苦瓜', icon: 'bitter-melon', category: '蔬菜' },
  { name: '上海青', icon: 'bok-choy', category: '蔬菜' },
  { name: '黄油', icon: 'butter', category: '乳制品' },
  { name: '卷心菜', icon: 'cabbage', category: '蔬菜' },
  { name: '哈密瓜', icon: 'cantaloupe', category: '水果' },
  { name: '樱桃', icon: 'cherry', category: '水果' },
  { name: '辣椒', icon: 'chili-pepper', category: '蔬菜' },
  { name: '山药', icon: 'chinese-yam', category: '蔬菜' },
  { name: '薯片', icon: 'chips', category: '零食' },
  { name: '巧克力', icon: 'chocolate', category: '零食' },
  { name: '香菜', icon: 'cilantro', category: '蔬菜' },
  { name: '椰子', icon: 'coconut', category: '水果' },
  { name: '饼干', icon: 'crackers', category: '零食' },
  { name: '火龙果', icon: 'dragon-fruit', category: '水果' },
  { name: '毛豆', icon: 'edamame', category: '蔬菜' },
  { name: '茄子', icon: 'eggplant', category: '蔬菜' },
  { name: '金针菇', icon: 'enoki-mushroom', category: '蔬菜' },
  { name: '蒜薹', icon: 'garlic-scape', category: '蔬菜' },
  { name: '四季豆', icon: 'green-beans', category: '蔬菜' },
  { name: '肉末', icon: 'ground-pork', category: '肉蛋' },
  { name: '山楂', icon: 'hawthorn', category: '水果' },
  { name: '蜂蜜', icon: 'honey', category: '其他' },
  { name: '猕猴桃', icon: 'kiwi', category: '水果' },
  { name: '龙眼', icon: 'longan', category: '水果' },
  { name: '莲藕', icon: 'lotus-root', category: '蔬菜' },
  { name: '丝瓜', icon: 'luffa', category: '蔬菜' },
  { name: '荔枝', icon: 'lychee', category: '水果' },
  { name: '橘子', icon: 'mandarin', category: '水果' },
  { name: '芒果', icon: 'mango', category: '水果' },
  { name: '大白菜', icon: 'napa-cabbage', category: '蔬菜' },
  { name: '坚果', icon: 'nuts', category: '零食' },
  { name: '桃子', icon: 'peach', category: '水果' },
  { name: '菠萝', icon: 'pineapple', category: '水果' },
  { name: '石榴', icon: 'pomegranate', category: '水果' },
  { name: '柚子', icon: 'pomelo', category: '水果' },
  { name: '猪肉', icon: 'pork', category: '肉蛋' },
  { name: '南瓜', icon: 'pumpkin', category: '蔬菜' },
  { name: '香菇', icon: 'shiitake', category: '蔬菜' },
  { name: '红薯', icon: 'sweet-potato', category: '蔬菜' },
  { name: '芋头', icon: 'taro', category: '蔬菜' },
  { name: '冬瓜', icon: 'winter-melon', category: '蔬菜' },
  { name: '木耳', icon: 'wood-ear', category: '蔬菜' },
  { name: '西葫芦', icon: 'zucchini', category: '蔬菜' },
  { name: '培根', icon: 'bacon', category: '肉蛋' },
  { name: '包子', icon: 'baozi', category: '主食' },
  { name: '牛肉', icon: 'beef', category: '肉蛋' },
  { name: '带鱼', icon: 'beltfish', category: '海鲜' },
  { name: '皮蛋', icon: 'century-egg', category: '肉蛋' },
  { name: '芝士片', icon: 'cheese-slices', category: '乳制品' },
  { name: '鸡胸肉', icon: 'chicken-breast', category: '肉蛋' },
  { name: '鸡腿', icon: 'chicken-leg', category: '肉蛋' },
  { name: '鸡翅', icon: 'chicken-wings', category: '肉蛋' },
  { name: '腊肠', icon: 'chinese-sausage', category: '肉蛋' },
  { name: '奶油', icon: 'cream', category: '乳制品' },
  { name: '挂面', icon: 'dried-noodles', category: '主食' },
  { name: '紫菜', icon: 'dried-seaweed', category: '海鲜' },
  { name: '豆干', icon: 'dried-tofu', category: '豆制品' },
  { name: '鸭蛋', icon: 'duck-eggs', category: '肉蛋' },
  { name: '鸭肉', icon: 'duck', category: '肉蛋' },
  { name: '豆腐乳', icon: 'fermented-tofu', category: '豆制品' },
  { name: '鱼丸', icon: 'fish-balls', category: '海鲜' },
  { name: '豆腐泡', icon: 'fried-tofu-puff', category: '豆制品' },
  { name: '糯米', icon: 'glutinous-rice', category: '主食' },
  { name: '牛肉末', icon: 'ground-beef', category: '肉蛋' },
  { name: '火腿', icon: 'ham', category: '肉蛋' },
  { name: '方便面', icon: 'instant-noodles', category: '主食' },
  { name: '海带', icon: 'kelp', category: '海鲜' },
  { name: '羊肉', icon: 'lamb', category: '肉蛋' },
  { name: '龙虾', icon: 'lobster', category: '海鲜' },
  { name: '奶粉', icon: 'milk-powder', category: '乳制品' },
  { name: '小米', icon: 'millet', category: '主食' },
  { name: '绿豆', icon: 'mung-beans', category: '主食' },
  { name: '燕麦', icon: 'oats', category: '主食' },
  { name: '生蚝', icon: 'oyster', category: '海鲜' },
  { name: '虾仁', icon: 'peeled-shrimp', category: '海鲜' },
  { name: '里脊', icon: 'pork-loin', category: '肉蛋' },
  { name: '鹌鹑蛋', icon: 'quail-eggs', category: '肉蛋' },
  { name: '红豆', icon: 'red-beans', category: '主食' },
  { name: '年糕', icon: 'rice-cake', category: '主食' },
  { name: '米粉', icon: 'rice-noodles', category: '主食' },
  { name: '咸鸭蛋', icon: 'salted-duck-egg', category: '肉蛋' },
  { name: '香肠', icon: 'sausage', category: '肉蛋' },
  { name: '扇贝', icon: 'scallop', category: '海鲜' },
  { name: '鲈鱼', icon: 'seabass', category: '海鲜' },
  { name: '鱿鱼', icon: 'squid', category: '海鲜' },
  { name: '牛排', icon: 'steak', category: '肉蛋' },
  { name: '馒头', icon: 'steamed-bun', category: '主食' },
  { name: '汤圆', icon: 'tangyuan', category: '主食' },
  { name: '吐司', icon: 'toast', category: '主食' },
  { name: '豆皮', icon: 'tofu-sheet', category: '豆制品' },
  { name: '腐竹', icon: 'tofu-skin', category: '豆制品' },
  { name: '淡奶油', icon: 'whipping-cream', category: '乳制品' },
  { name: '黄鱼', icon: 'yellow-croaker', category: '海鲜' },
  { name: '杏仁', icon: 'almonds', category: '干货' },
  { name: '苹果汁', icon: 'apple-juice', category: '饮料' },
  { name: '白酒', icon: 'baijiu', category: '酒水' },
  { name: '泡打粉', icon: 'baking-powder', category: '烘焙' },
  { name: '啤酒', icon: 'beer', category: '酒水' },
  { name: '红茶', icon: 'black-tea', category: '饮料' },
  { name: '香醋', icon: 'black-vinegar', category: '调料' },
  { name: '蛋糕', icon: 'cake', category: '零食' },
  { name: '糖果', icon: 'candy', category: '零食' },
  { name: '鱼罐头', icon: 'canned-fish', category: '方便食品' },
  { name: '腰果', icon: 'cashews', category: '干货' },
  { name: '鸡精', icon: 'chicken-bouillon', category: '调料' },
  { name: '辣椒粉', icon: 'chili-powder', category: '调料' },
  { name: '辣椒酱', icon: 'chili-sauce', category: '调料' },
  { name: '可可粉', icon: 'cocoa-powder', category: '烘焙' },
  { name: '椰汁', icon: 'coconut-drink', category: '饮料' },
  { name: '咖啡豆', icon: 'coffee-beans', category: '饮料' },
  { name: '咖啡', icon: 'coffee', category: '饮料' },
  { name: '八宝粥', icon: 'congee-can', category: '方便食品' },
  { name: '淀粉', icon: 'cornstarch', category: '调料' },
  { name: '孜然', icon: 'cumin', category: '调料' },
  { name: '干辣椒', icon: 'dried-chili', category: '调料' },
  { name: '干香菇', icon: 'dried-shiitake', category: '干货' },
  { name: '功能饮料', icon: 'energy-drink', category: '饮料' },
  { name: '薯条', icon: 'french-fries', category: '速冻' },
  { name: '吉利丁', icon: 'gelatin', category: '烘焙' },
  { name: '枸杞', icon: 'goji-berries', category: '干货' },
  { name: '火腿肠', icon: 'ham-sausage', category: '方便食品' },
  { name: '火锅丸子', icon: 'hotpot-balls', category: '速冻' },
  { name: '火锅底料', icon: 'hotpot-base', category: '调料' },
  { name: '冰淇淋', icon: 'ice-cream', category: '速冻' },
  { name: '速溶咖啡', icon: 'instant-coffee', category: '饮料' },
  { name: '果冻', icon: 'jelly', category: '零食' },
  { name: '辣条', icon: 'latiao', category: '零食' },
  { name: '棒棒糖', icon: 'lollipop', category: '零食' },
  { name: '午餐肉', icon: 'luncheon-meat', category: '方便食品' },
  { name: '味精', icon: 'msg', category: '调料' },
  { name: '橙汁', icon: 'orange-juice', category: '饮料' },
  { name: '花生', icon: 'peanuts', category: '干货' },
  { name: '胡椒粉', icon: 'pepper-powder', category: '调料' },
  { name: '爆米花', icon: 'popcorn', category: '零食' },
  { name: '糖粉', icon: 'powdered-sugar', category: '烘焙' },
  { name: '葡萄干', icon: 'raisins', category: '干货' },
  { name: '红枣', icon: 'red-dates', category: '干货' },
  { name: '红酒', icon: 'red-wine', category: '酒水' },
  { name: '黄酒', icon: 'rice-wine', category: '酒水' },
  { name: '海苔', icon: 'seaweed-snack', category: '零食' },
  { name: '芝麻油', icon: 'sesame-oil', category: '调料' },
  { name: '芝麻', icon: 'sesame', category: '调料' },
  { name: '苏打水', icon: 'soda-water', category: '饮料' },
  { name: '黄豆酱', icon: 'soybean-paste', category: '调料' },
  { name: '黄豆', icon: 'soybeans', category: '干货' },
  { name: '气泡水', icon: 'sparkling-water', category: '饮料' },
  { name: '雪碧', icon: 'sprite', category: '饮料' },
  { name: '瓜子', icon: 'sunflower-seeds', category: '干货' },
  { name: '甜面酱', icon: 'sweet-bean-sauce', category: '调料' },
  { name: '茶包', icon: 'tea-bags', category: '饮料' },
  { name: '茶叶', icon: 'tea-leaves', category: '饮料' },
  { name: '醋', icon: 'vinegar', category: '调料' },
  { name: '核桃', icon: 'walnuts', category: '干货' },
  { name: '银耳', icon: 'white-fungus', category: '干货' },
  { name: '馄饨', icon: 'wonton', category: '速冻' },
  { name: '酵母', icon: 'yeast', category: '烘焙' },
  { name: '乳酸菌', icon: 'yogurt-drink', category: '饮料' },
  { name: '锡纸', icon: 'aluminum-foil', category: '日用' },
  { name: '电池', icon: 'batteries', category: '日用' },
  { name: '身体乳', icon: 'body-lotion', category: '个护' },
  { name: '扫把', icon: 'broom', category: '日用' },
  { name: '抹布', icon: 'cleaning-cloth', category: '日用' },
  { name: '梳子', icon: 'comb', category: '个护' },
  { name: '化妆棉', icon: 'cotton-pads', category: '个护' },
  { name: '棉签', icon: 'cotton-swabs', category: '个护' },
  { name: '牙线', icon: 'dental-floss', category: '个护' },
  { name: '消毒液', icon: 'disinfectant', category: '日用' },
  { name: '一次性手套', icon: 'disposable-gloves', category: '日用' },
  { name: '柔顺剂', icon: 'fabric-softener', category: '日用' },
  { name: '面霜', icon: 'face-cream', category: '个护' },
  { name: '洗面奶', icon: 'face-wash', category: '个护' },
  { name: '保鲜袋', icon: 'food-bags', category: '日用' },
  { name: '护手霜', icon: 'hand-cream', category: '个护' },
  { name: '洗衣液', icon: 'laundry-detergent', category: '日用' },
  { name: '洗衣粉', icon: 'laundry-powder', category: '日用' },
  { name: '拖把', icon: 'mop', category: '日用' },
  { name: '漱口水', icon: 'mouthwash', category: '个护' },
  { name: '餐巾纸', icon: 'napkins', category: '日用' },
  { name: '剃须刀', icon: 'razor', category: '个护' },
  { name: '卫生巾', icon: 'sanitary-pads', category: '个护' },
  { name: '百洁布', icon: 'scrub-sponge', category: '日用' },
  { name: '香皂', icon: 'soap-bar', category: '个护' },
  { name: '防晒霜', icon: 'sunscreen', category: '个护' },
  { name: '洁厕灵', icon: 'toilet-cleaner', category: '日用' },
  { name: '牙签', icon: 'toothpicks', category: '日用' },
  { name: '垃圾桶', icon: 'trash-can', category: '日用' },
  { name: '湿巾', icon: 'wet-wipes', category: '日用' },
  { name: '密封袋', icon: 'ziplock-bags', category: '日用' },
];

export const UNIQUE_ICON_ITEMS = ICON_ITEMS;

export function getIconPath(name: string): string | null {
  const key = normalizeName(name);
  const exact = ICON_ITEMS.find(
    i => normalizeName(i.name) === key || i.aliases?.some(a => normalizeName(a) === key)
  );
  if (exact) return `/icons/${exact.icon}.webp`;
  const partial = ICON_ITEMS.find(
    i => key.includes(normalizeName(i.name)) || normalizeName(i.name).includes(key)
  );
  if (partial) return `/icons/${partial.icon}.webp`;
  return null;
}

/**
 * Resolve icon URL with custom icon support.
 * Priority: custom icon → preset icon → null (caller renders WatercolorFallback)
 */
export function resolveIconUrl(
  name: string,
  customIconMap?: Map<string, string>
): string | null {
  // 1. Custom icon (user's explicit choice for this list, may override preset)
  if (customIconMap) {
    const custom = customIconMap.get(normalizeName(name));
    if (custom) return custom;
  }
  // 2. Preset icon
  const preset = getIconPath(name);
  if (preset) return preset;
  // 3. No match — caller should render WatercolorFallback
  return null;
}

export function iconExists(icon: string): boolean {
  try {
    const img = new Image();
    img.src = `/icons/${icon}.png`;
    return true;
  } catch {
    return false;
  }
}
